// <auto-generated />
using FIAP.FaseUm.TechChallenge.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIAP.FaseUm.TechChallenge.Infra.Data.Migrations
{
    [DbContext(typeof(TechChallengeFaseUmDbContext))]
    partial class TechChallengeFaseUmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIAP.FaseUm.TechChallenge.Domain.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.HasKey("Id");

                    b.ToTable("Contatos", (string)null);
                });

            modelBuilder.Entity("FIAP.FaseUm.TechChallenge.Domain.Entities.Contato", b =>
                {
                    b.OwnsOne("FIAP.FaseUm.TechChallenge.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ContatoId")
                                .HasColumnType("INT");

                            b1.Property<string>("Endereco")
                                .IsRequired()
                                .HasColumnType("VARCHAR(150)")
                                .HasColumnName("Email");

                            b1.HasKey("ContatoId");

                            b1.ToTable("Contatos");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.OwnsOne("FIAP.FaseUm.TechChallenge.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<int>("ContatoId")
                                .HasColumnType("INT");

                            b1.Property<string>("Ddd")
                                .IsRequired()
                                .HasColumnType("VARCHAR(5)")
                                .HasColumnName("DddTelefone");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("VARCHAR(50)")
                                .HasColumnName("NumeroTelefone");

                            b1.HasKey("ContatoId");

                            b1.ToTable("Contatos");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
