services:
  fiap.faseum.techchallenge.api:
    container_name: api_fiap
    image: ${DOCKER_REGISTRY-}fiapfaseumtechchallengeapi
    build:
      context: .
      dockerfile: src/FIAP.FaseUm.TechChallenge.Api/Dockerfile
    depends_on:
      - sql-server
    networks:
      - fiap_network
    command: sh -c "sleep 10 && dotnet ef database update && dotnet FIAP.FaseUm.TechChallenge.Api.dll"

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Senha@123
    ports:
      - "1433:1433"
    networks:
      - fiap_network
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Senha@123"]
      interval: 10s
      retries: 5

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus_data:/prometheus"
    networks:
      - fiap_network
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
  
  node-exporter:
    image: prom/node-exporter
    networks:
      - fiap_network
    ports:
      - 9100:9100
 
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - fiap_network

networks:
  fiap_network:
    driver: bridge

volumes:
  sqlserver-data:
  prometheus_data:
  grafana_data:
  