{
 "title": "ASP.NET Core",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(microsoft_aspnetcore_hosting_http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(microsoft_aspnetcore_hosting_http_server_active_requests{job=~\"webapp\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests By Status Code",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (max_over_time(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\"}[$__interval]))",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\", http_response_status_code=~\"4..|5..\"}[$__interval]) or vector(0)) / sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\", http_response_status_code=~\"4..\"}[$__interval]) or vector(0)) / sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\", http_response_status_code=~\"5..\"}[$__interval]) or vector(0)) / sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Total Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"webapp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\", error_type!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Secured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    max_over_time(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\"}[$__interval])\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "Requests HTTP Protocol",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(max_over_time(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\"}[$__interval]), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"webapp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Unhandled Exception Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(max_over_time(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\", http_route!=\"\", error_type!=\"\"}[$__interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{job=\"webapp\"}[$__interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(microsoft_aspnetcore_server_kestrel_current_connections{job=\"webapp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "sum(microsoft_aspnetcore_hosting_http_server_active_requests{job=\"webapp\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(max_over_time(microsoft_aspnetcore_hosting_http_server_request_duration_count{job=\"webapp\", http_route!=\"\"}[$__interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}