name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore FIAP.FaseUm.TechChallenge.sln

    - name: Build
      run: dotnet build FIAP.FaseUm.TechChallenge.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test FIAP.FaseUm.TechChallenge.sln --no-restore --verbosity normal --configuration Release
